<?php

/**
 * This script is used to import data from a CSV file containing zip codes and related information into a MySQL database.
 * It generates an SQL file with the necessary INSERT statements to populate the 'locus' table.
 * The CSV file should have the following columns: zip, label, isSub, commune, province.
 * The script also requires a 'create_table.sql' file to be present in the same directory.
 * 
 * Usage:
 * php locus.php -i [input_csv_file] -o [output_sql_file]
 * 
 * If no input or output file is specified, default values will be used.
 * 
 * @link https://www.bpost.be/fr/outil-de-validation-de-codes-postaux Télécharger codes postaux
 * @link https://www.belgium.be/fr/la_belgique/pouvoirs_publics/provinces Code des provinces
 */

const CREATE_TABLE_FILENAME = 'create_table.sql';
const DEFAULT_CSV_IN = __DIR__.'/zipcodes_alpha_fr_new.csv';
const DEFAULT_SQL_OUT = __DIR__.'/locus.sql';

$options = getopt("i:o:");

$csv_in = $options['i'] ?? DEFAULT_CSV_IN;
$sql_out = $options['o'] ?? DEFAULT_SQL_OUT;

// test if create_table exists
if(!file_exists(CREATE_TABLE_FILENAME)) die(CREATE_TABLE_FILENAME.' not found');

// open the sql_out file in write mode
$out = fopen($sql_out, 'w');
if(!$out) die('Unable to open output file: '.$sql_out);

// write the comment and the content of create_table.sql
fwrite($out, sprintf('-- GENERATED BY %s ON %s', 'locus/locus.php', date('Y-m-d H:i:s')));

fwrite($out, PHP_EOL);
fwrite($out, '-- DO NOT EDIT');

fwrite($out, PHP_EOL);
fwrite($out, PHP_EOL);
fwrite($out, file_get_contents('create_table.sql'));

fwrite($out, PHP_EOL);


// open the csv_in file in read mode
$in = fopen($csv_in, 'r');
if(!$in) {
    fwrite($out, '-- Unable to open input file: '.$in);
    fclose($out);
    die('Unable to open input file: '.$in);
}

fwrite($out, <<<SQL


--
--
-- CONTENT FOLLOWS
--
--


SQL);
fwrite($out, PHP_EOL);
fwrite($out, PHP_EOL);

fwrite($out, 'INSERT INTO `locus` (`zip`, `label`, `isSub`, `commune`, `province`)');
fwrite($out, ' VALUES ');

$headers = fgets($in); // skip headers
$count = 0;
$line = fgets($in);
while($line !== false) {
  ++$count;
  
  list($zip, $label, $isSub, $commune, $province) = explode(',', trim($line));

  $isSub = ($isSub == '"Oui"') ? 1 : (($isSub == '"Non"') ? 0 : 'NULL');
  $province = empty($province) ? 'NULL' : $province;

  fwrite($out, sprintf('(%d, %s, %s, %s, %s)', $zip, $label, $isSub, $commune, $province));

  $line = fgets($in);
  if($line !== false) 
    fwrite($out, ',');

  fwrite($out, PHP_EOL);
}
fclose($in);

$goodbye = 'END OF FILE (#'.$count.')'.PHP_EOL;

fwrite($out, '-- '.$goodbye);
fclose($out);

die($goodbye);