<?php
/*

Télécharger codes postaux
https://www.bpost.be/fr/outil-de-validation-de-codes-postaux

Code des provinces
https://www.belgium.be/fr/la_belgique/pouvoirs_publics/provinces

*/

$comment = "
-- GENERATED BY locus/locus.php
-- DO NOT EDIT
";

$csv_in = __DIR__.'/zipcodes_alpha_fr_new.csv';
$sql_out = __DIR__.'/../001_locus.sql';

$csv_in = trim(file_get_contents($csv_in));
$csv_in = explode(PHP_EOL, $csv_in);
array_shift($csv_in); // remove headers
$insert = [];

$insert_query = 'INSERT INTO `locus` (`zip`, `label`, `isSub`, `commune`, `province`) VALUES ';
foreach($csv_in as $locus)
{
  // "Code postal","Localité","Sous-commune","Commune Principale","Province"
  list($zip, $label, $isSub, $commune, $province) = explode(',', $locus);
  $isSub = ($isSub == '"Oui"') ? 1 : (($isSub == '"Non"') ? 0 : 'NULL');
  $province = empty($province) ? 'NULL' : $province;
  $inserts[]= sprintf('(%d, %s, %s, %s, %s)', $zip, $label, $isSub, $commune, $province);
}

$insert_query .= PHP_EOL.implode(','.PHP_EOL, $inserts) . ';';

$create_table = file_get_contents('create_table.sql');
file_put_contents($sql_out, $comment.PHP_EOL.$create_table.PHP_EOL.$insert_query);

?>
