<?php
/*

Télécharger codes postaux
https://www.bpost.be/fr/outil-de-validation-de-codes-postaux

Code des provinces
https://www.belgium.be/fr/la_belgique/pouvoirs_publics/provinces

*/

$comment = sprintf('-- GENERATED BY %s ON %s', 'locus/locus.php', date('Y-m-d H:i:s'));
$comment.= PHP_EOL.'-- DO NOT EDIT';


$options = getopt("i:o:");

$csv_in = $options['i'] ?? __DIR__.'/zipcodes_alpha_fr_new.csv';
$sql_out = $options['o'] ?? __DIR__.'/../001_locus.sql';

$insert = [];

$insert_query = 'INSERT INTO `locus` (`zip`, `label`, `isSub`, `commune`, `province`) VALUES ';
foreach(loadCSV($csv_in) as $locus)
{
  // "Code postal","Localité","Sous-commune","Commune Principale","Province"
  list($zip, $label, $isSub, $commune, $province) = explode(',', trim($locus));
  $isSub = ($isSub == '"Oui"') ? 1 : (($isSub == '"Non"') ? 0 : 'NULL');
  $province = empty($province) ? 'NULL' : $province;
  $inserts[]= sprintf('(%d, %s, %s, %s, %s)', $zip, $label, $isSub, $commune, $province);
}

$insert_query .= PHP_EOL.implode(','.PHP_EOL, $inserts) . ';';

$create_table = file_get_contents('create_table.sql');
$create_table .= <<<SQL


--
--
-- CONTENT FOLLOWS
--
--


SQL;


file_put_contents($sql_out, $comment.PHP_EOL.$create_table.PHP_EOL.$insert_query);

function loadCSV($filename){

  $csv_in = fopen($filename, 'r');
  $csv_data = [];
  while (($line = fgets($csv_in)) !== false) {
    $csv_data[] = $line;
  }
  fclose($csv_in);
  array_shift($csv_data); // remove headers

  return $csv_data;
}
?>
